### ISSUE TITLE
Error message on creating task for assets/shots on short production @ TNZPV

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#162]
==> gunicorn_error.log <==
[2018-11-20 16:23:30 +0100] [3643] [ERROR] Error handling request //actions/task-types/51c13216-5853-45ad-bbd8-2f0bcd38232a/assets/create-tasks?project_id=2b4f876e-dc20-457b-b909-c895ccab0414
Traceback (most recent call last):
  File "/opt/zou2/zouenv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/zou2/zouenv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "ix_task_status_short_name"
DETAIL:  Key (short_name)=(todo) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/zou2/zouenv/lib/python3.5/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/opt/zou2/zouenv/lib/python3.5/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/opt/zou2/zouenv/lib/python3.5/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/zou2/zouenv/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/zou2/zouenv/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/zou2/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou2/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou2/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/opt/zou2/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)

c'est tronqué
bref
l'erreur suivante

sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "ix_task_status_short_name"
DETAIL:  Key (short_name)=(todo) already exists.
 [SQL: 'INSERT INTO task_status (id, created_at, updated_at, name, short_name, color, is_reviewable, is_done, shotgun_id) VALUES (%(id)s, %(created_at)s, %(updated_at)s, %(name)s, %(short_name)s, %(color)s, %(is_reviewable)s, %(is_done)s, %(shotgun_id)s)'] [parameters: {'id': UUID('e07d58c9-b9b5-4942-9f39-cb7b17d173ee'), 'created_at': datetime.datetime(2018, 11, 20, 15, 23, 30, 452567), 'shotgun_id': None, 'short_name': 'todo', 'color': '#f5f5f5', 'is_reviewable': False, 'updated_at': datetime.datetime(2018, 11, 20, 15, 23, 30, 452572), 'name': 'Todo', 'is_done': False}] (Background on this error at: http://sqlalche.me/e/gkpj)

**Comment by frankrousseau** [comment]
We fixed that problem with TNZPV. They didn't run the data initialisation script.
