### ISSUE TITLE
nodejs no run

### ISSUE THREAD

**Issue by lymanzhao** [cgwire/kitsu#266]
> kitsu@0.1.0 start /opt/kitsu
> node build/dev-server.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/opt/kitsu/build/dev-server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kitsu@0.1.0 start: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kitsu@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oct2/.npm/_logs
[2019-08-13T04_01_26_184Z-debug.log](https://github.com/cgwire/kitsu/files/3495295/2019-08-13T04_01_26_184Z-debug.log)

/2019-08-13T04_01_26_184Z-debug.log

**Comment by frankrousseau** [comment]
You should not use Nodejs to run Kitsu. Full installation documentation is available here: https://zou.cg-wire.com/
