### ISSUE TITLE
Can't select another shots in Breakdown Views

### ISSUE THREAD

**Issue by aditiapratama** [cgwire/kitsu#291]
Steps to reproduce this error:
- open breakdown views
- select shot
- then select another shot

i've got the following error in console
```javascript
DevTools failed to parse SourceMap: http://34.87.4.10/css/bulma.css.map
Breakdown.vue:417 options changed [__ob__: It]
Breakdown.vue:417 options changed [__ob__: It]
Breakdown.vue:417 options changed [{…}, __ob__: It]
Breakdown.vue:417 options changed [{…}, __ob__: It]
client.js?6f66e68:16 [WARNING] Crisp found shims of native JavaScript methods. This can alter the chatbox behavior and break things. Make sure not to override listed functions to ensure your chatbox works as expected. You may be looking for other JavaScript libraries in use on this page.

You can disable this warning by adding: $crisp.push(["safe", true]) to your page JavaScript.

Methods to check: ["document.createElement"]
Crisp.Polyfill.e.__warn_incompatible @ client.js?6f66e68:16
(anonymous) @ client.js?6f66e68:16
setTimeout (async)
Crisp.Polyfill.e.schedule_warn_incompatible @ client.js?6f66e68:16
Crisp.Base.e._trigger_session_loaded @ client.js?6f66e68:19
(anonymous) @ client.js?6f66e68:17
r @ client.js?6f66e68:12
n @ client.js?6f66e68:12
(anonymous) @ client.js?6f66e68:12
setTimeout (async)
_ @ client.js?6f66e68:12
e.publish @ client.js?6f66e68:12
e.handle_state @ client.js?6f66e68:8
e.get_state @ client.js?6f66e68:8
(anonymous) @ client.js?6f66e68:17
r @ client.js?6f66e68:12
n @ client.js?6f66e68:12
(anonymous) @ client.js?6f66e68:12
setTimeout (async)
_ @ client.js?6f66e68:12
e.publish @ client.js?6f66e68:12
e.__publish_users_available @ client.js?6f66e68:9
e.get_users_available @ client.js?6f66e68:9
(anonymous) @ client.js?6f66e68:17
(anonymous) @ client.js?6f66e68:19
Crisp.Locale.e.__handle_locale_injection @ client.js?6f66e68:17
(anonymous) @ client.js?6f66e68:17
_dollar_crisp.__spool.<computed> @ client.js?6f66e68:19
(anonymous) @ en.js?6f66e68:7
vue-router.esm.js:2051 Uncaught (in promise) e {_name: "NavigationDuplicated", name: "NavigationDuplicated", message: "Navigating to current location ("/productions/d84b…9-efb51dc6be35/breakdown/shot_id") is not allowed", stack: "Error↵    at new e (http://34.87.4.10/js/chunk-ven…34.87.4.10/js/chunk-vendors.1e02ee80.js:64:19390)"}
(anonymous) @ vue-router.esm.js:2051
c @ vue-router.esm.js:2082
qt.confirmTransition @ vue-router.esm.js:2090
qt.transitionTo @ vue-router.esm.js:2034
e.push @ vue-router.esm.js:2365
(anonymous) @ vue-router.esm.js:2779
he.push @ vue-router.esm.js:2778
selectShot @ Breakdown.vue:317
Me @ vue.js:1863
n @ vue.js:2188
Me @ vue.js:1863
t.$emit @ vue.js:3883
onClicked @ ShotLine.vue:33
Me @ vue.js:1863
n @ vue.js:2188
o._wrapper @ vue.js:7541

```

With error line specifically on line `40` as follows `vue-router.esm.js:2051 Uncaught (in promise) e {_name: "NavigationDuplicated", name: "NavigationDuplicated", message: "Navigating to current location ("/productions/d84b…9-efb51dc6be35/breakdown/shot_id") is not allowed", stack: "Error↵    at new e (http://34.87.4.10/js/chunk-ven…34.87.4.10/js/chunk-vendors.1e02ee80.js:64:19390)"}
`

**Comment by frankrousseau** [comment]
Thank you @aditiapratama for reporting. We will perform a redesign of the breakdown module navigation next week. It will fix this problem.

**Comment by frankrousseau** [comment]
Can you update your install and try again?

**Comment by aditiapratama** [comment]
@frankrousseau Thank you it working now

**Comment by frankrousseau** [comment]
Great!
