### ISSUE TITLE
Build MP4 From Playlist Error

### ISSUE THREAD

**Issue by clarkjohn2989** [cgwire/kitsu#312]
i'm trying to build mp4 from a playlist that contains 3 shots, but it keeps loading with no result to download
But the option of zip download is working with no issues
**Here is a screenshot of the problem:**
![hahaha](https://user-images.githubusercontent.com/57597072/68547496-e8221600-03ea-11ea-892e-0baebc678dde.PNG)

**and the server traceback of zou error log:**
[2019-11-10 18:25:47,755] ERROR in __init__: Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_jwt_extended/view_decorators.py", line 103, in wrapper
    return fn(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/blueprints/playlists/resources.py", line 121, in get
    playlists_service.build_playlist_movie_file(playlist)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/services/playlists_service.py", line 326, in build_playlist_movie_file
    file_store.add_movie("playlists", job["id"], movie_file_path)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/stores/file_store.py", line 132, in add_movie
    with open(path, "rb") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/zou/cache-playlists-cd9066bb-aad3-427b-9982-fb652a59f9bc.mp4'

**Comment by frankrousseau** [comment]
It's hard to tell what is going wrong. If you can send us the problematic files, it would help.

**Comment by frankrousseau** [comment]
It may be due to the fact that there is no sound included in your movies. We noticed that problem on other installation. An audio track is required on each movies.

**Comment by gwendupre** [comment]
@clarkjohn2989 can you retry with sound enable on your video?
