### ISSUE TITLE
cant login to kitsu

### ISSUE THREAD

**Issue by Aderemi-Adesada** [cgwire/kitsu#567]
I keep getting an error that the password is wrong.
this is my log
`[2020-11-06 11:43:11,788] ERROR in auth_service: Wrong password for person: Super Admin`
`[2020-11-06 11:43:45,803] ERROR in resources: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "/opt/zou/zou/app/blueprints/auth/resources.py", line 203, in post
    access_token = create_access_token(identity=user["email"])
  File "/opt/zouenv/lib/python3.8/site-packages/Flask_JWT_Extended-3.20.0-py3.8.egg/flask_jwt_extended/utils.py", line 157, in create_access_token
    return jwt_manager._create_access_token(identity, fresh, expires_delta, user_claims)
  File "/opt/zouenv/lib/python3.8/site-packages/Flask_JWT_Extended-3.20.0-py3.8.egg/flask_jwt_extended/jwt_manager.py", line 469, in _create_access_token
    access_token = encode_access_token(
  File "/opt/zouenv/lib/python3.8/site-packages/Flask_JWT_Extended-3.20.0-py3.8.egg/flask_jwt_extended/tokens.py", line 76, in encode_access_token
    return _encode_jwt(token_data, expires_delta, secret, algorithm,
  File "/opt/zouenv/lib/python3.8/site-packages/Flask_JWT_Extended-3.20.0-py3.8.egg/flask_jwt_extended/tokens.py", line 30, in _encode_jwt
    encoded_token = jwt.encode(token_data, secret, algorithm,
AttributeError: 'str' object has no attribute 'decode'`

**Comment by frankrousseau** [comment]
Hello @Aderemi-Adesada, there is probably an issue with your installation.
