### ISSUE TITLE
Broken previews when file has no audio track

### ISSUE THREAD

**Issue by LarsCawley** [cgwire/kitsu#646]
Today we are having trouble posting previews. Zou 0.12.50 Kitsu 0.12.52
I noticed Kitsu was trying to make a preview in /opt/zou/previews/movies/lowdef which didn't exist.  I created it, but it still isn't happy.

```
[2021-03-01 17:41:01,934] ERROR in preview_files_service: b"ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 9 (Ubuntu 9.3.0-10u>
[2021-03-01 17:41:01,935] ERROR in preview_files_service: failed
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/services/preview_files_service.py", line 97, in prepare_and_store_movie
    ) = movie.normalize_movie(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/utils/movie.py", line 109, in normalize_movie
    stream.run(quiet=False, capture_stderr=True)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
[2021-03-01 17:41:29,620] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/movies/lowdef/352/7a7/3527a717-3962-43ee-ac56-b18e479636ee'
[2021-03-01 17:41:29,663] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/movies/lowdef/352/7a7/3527a717-3962-43ee-ac56-b18e479636ee'
```

**Comment by frankrousseau** [comment]
Hello @LarsCawley. Is it just something that appears into your log or are you telling that you don't see any previews in the UI?

**Comment by LarsCawley** [comment]
Hi @frankrousseau in the UI the comment is registered bit the preview window shows a message that the preview is broken.

**Comment by frankrousseau** [comment]
Are you sure that the folder have proper rights?

**Comment by LarsCawley** [comment]
Yes, it has the same rights as the existing previews dir and ownership is zou:www-data.  I shouldn't have to make this directory though should I?  Our previews have been working fine until the recent update.

**Comment by LarsCawley** [comment]
Actually perhaps this is the problem ( it was trimmed from the original error I posted because I didn't wrap the log's long lines):

```
[2021-03-04 17:11:13,945] ERROR in preview_files_service: b"ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)\n
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --dis
able-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --ena
ble-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --ena
ble-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnap
py --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp
 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-li
bdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 31.100 / 56. 31.100\n  libavcode
c     58. 54.100 / 58. 54.100\n  libavformat    58. 29.100 / 58. 29.100\n  libavdevice    58.  8.100 / 58.  8.100\n  libavfilter     7. 57.100 /  7. 57.100\n  libavresample   4.  0.  0
 /  4.  0.  0\n  libswscale      5.  5.100 /  5.  5.100\n  libswresample   3.  5.100 /  3.  5.100\n  libpostproc    55.  5.100 / 55.  5.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from '/t
mp/zou/bed5176a-c31d-467b-b374-8e17d1eb9a32.mov.tmp':\n  Metadata:\n    major_brand     : qt  \n    minor_version   : 512\n    compatible_brands: qt  \n    uk.co.thefoundry.Application
: Nuke\n    uk.co.thefoundry.ApplicationVersion: 10.0v4\n    uk.co.thefoundry.YCbCrMatrix: Rec 709\n    uk.co.thefoundry.Colorspace: rec709\n    uk.co.thefoundry.Writer: mov64\n  Durat
ion: 00:00:02.96, start: 0.000000, bitrate: 58141 kb/s\n    Stream #0:0(eng): Video: dnxhd (DNXHD) (AVdn / 0x6E645641), yuv422p(pc, bt709/unknown/unknown), 1280x720, 58137 kb/s, SAR 1:
1 DAR 16:9, 23.98 fps, 23.98 tbr, 24k tbn, 24k tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\n      encoder         : DNxHD\nStream map '0:a' matches no streams.\n
To ignore this, add a trailing '?' to the map.\n"
[2021-03-04 17:11:13,945] ERROR in preview_files_service: failed
```

**Comment by frankrousseau** [comment]
If you can send me the wrong video in any way, that would help.

**Comment by frankrousseau** [comment]
I think its fixed in the last version of Zou.

**Comment by LarsCawley** [comment]
Yes, fixed now.  Thank you.
